easy_admin:
  site_name: 'Une année de voyages'
  entities:
    Article:
      class: App\Entity\Article
      label: 'Article'
      form:
        fields:
          - title
          - content
          - shortDescription
          - tags
          - articleCategory
    Hostel:
      class: App\Entity\Hostel
      label: 'Hôtel'
      form:
        fields:
          - title
          - content
          - shortDescription
          - tags
    Restaurant:
      class: App\Entity\Restaurant
      label: 'Restaurant'
      form:
        fields:
          - title
          - content
          - shortDescription
          - tags
    SPA:
      class: App\Entity\SPA
      label: 'SPA'
      form:
        fields:
          - title
          - content
          - shortDescription
          - tags
    ArticleCategory:
      class: App\Entity\ArticleCategory
      label: 'Categorie Article'
  design:
    color_scheme: 'light'
    brand_color: 'rgba(26, 188, 156, 0.85)'